name: rayhan_erp
description: ERP Sur Mesure — SUARL Rayhan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  intl: ^0.19.0
  fl_chart: ^0.67.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  package_info_plus: ^10.1.0
  pdf: ^3.10.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/InterItalic.ttf
          style: italic
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800